name: actions-pipx
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
jobs:
  test-action:
    uses: ./.github/workflows/test_action.yml
  lint-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ci-pass:
    name: CI is green
    runs-on: ubuntu-latest
    needs:
      - lint-pr
      - test-action
    steps:
      - run: exit 0
