name: Test actions-pipx action
on:
  workflow_call:
jobs:
  run:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-18.04, ubuntu-20.04, windows-2019, windows-2022, macos-11,macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipx
        uses: ./
        with:
          pipx-version: 1.0.0
      - name: View pipx --help
        run: pipx --help
      - name: check pipx is in path
        run: pipx ensurepath
      - name: run pycowsay
        run: pipx run pycowsay
  